#!/usr/bin/env python3
"""Export lingvichr's SVG logo to web, auth, admin, and native app assets.

Run from any directory with Python, Pillow, and rsvg-convert installed.
Edit assets/branding/logo.svg, then rerun this script to update the exports.
"""

import io
import json
import subprocess
from pathlib import Path
from urllib.parse import quote
from xml.etree import ElementTree

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
LOGO = (ROOT / "assets/branding/logo.svg").read_text()
PATHS = list(ElementTree.fromstring(LOGO))
SVG_BODY = LOGO.split(">", 1)[1].rsplit("</svg>", 1)[0]
APP_ICON = (
    '<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 64 64">'
    '<rect width="64" height="64" fill="#000"/>'
    f'<g transform="translate(6.4 6.4) scale(.8)">{SVG_BODY}</g></svg>\n'
)


def write(relative_path: str, content: str) -> None:
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def png(size: int) -> bytes:
    return subprocess.run(
        ["rsvg-convert", "--width", str(size), "--height", str(size)],
        input=APP_ICON.encode(), capture_output=True, check=True,
    ).stdout


def android_vector(size: str, group: str) -> str:
    attributes = {
        "d": "pathData", "fill": "fillColor", "stroke": "strokeColor",
        "stroke-width": "strokeWidth", "stroke-linejoin": "strokeLineJoin",
    }
    paths = []
    for path in PATHS:
        values = []
        for name, value in path.attrib.items():
            # VectorDrawable uses transparent rather than SVG's fill="none".
            if value == "none":
                value = "#00000000"
            values.append(f'android:{attributes[name]}="{value}"')
        paths.append("        <path " + " ".join(values) + " />")
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size}dp" android:height="{size}dp"\n'
        f'    android:viewportWidth="{size if size == "108" else "64"}" '
        f'android:viewportHeight="{size if size == "108" else "64"}">\n'
        f'    <group {group}>\n' + "\n".join(paths) + "\n    </group>\n</vector>\n"
    )


write("apps/web/public/logo.svg", LOGO)
write("apps/web/public/icon.svg", APP_ICON)
write("apps/admin/public/icon.svg", APP_ICON)
for size in [180, 192, 512]:
    (ROOT / f"apps/web/public/icon-{size}.png").write_bytes(png(size))
(ROOT / "apps/web/public/icon-preview.png").write_bytes(png(512))
with Image.open(io.BytesIO(png(256))) as image:
    image.save(ROOT / "apps/web/public/favicon.ico", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])

icon_set = ROOT / "apps/ios/Flashcards/Flashcards/Assets.xcassets/AppIcon.appiconset"
for entry in json.loads((icon_set / "Contents.json").read_text())["images"]:
    size = round(float(entry["size"].split("x")[0]) * float(entry["scale"].removesuffix("x")))
    with Image.open(io.BytesIO(png(size))) as image:
        # Apple's app icons must be opaque and let the OS apply the icon mask.
        image.convert("RGB").save(icon_set / entry["filename"])

write("apps/android/app/src/main/res/drawable/ic_launcher_foreground.xml", android_vector(
    "108", 'android:translateX="26" android:translateY="26" android:scaleX="0.875" android:scaleY="0.875"',
))
write("apps/android/app/src/main/res/drawable/ic_brand_logo_splash.xml", android_vector(
    "240", 'android:pivotX="32" android:pivotY="32" android:scaleX="0.72" android:scaleY="0.72"',
))

write("apps/auth/src/templates/branding.ts", (
    '// Generated by scripts/generate/brand-assets.py from assets/branding/logo.svg.\n'
    f'export const authFaviconUrl: string = {json.dumps("data:image/svg+xml," + quote(APP_ICON, safe=""))};\n'
    f'export const authLogoUrl: string = {json.dumps("data:image/svg+xml," + quote(LOGO, safe=""))};\n'
    '\nexport const authBrandHtml: string = `<div class="login-brand" dir="ltr">'
    '<img src="${authLogoUrl}" width="32" height="32" alt="">'
    '<span>lingvichr</span></div>`;\n'
))
print("Generated web, auth, admin, Android, and iOS branding assets.")
